### ISSUE TITLE
Figma draft design v1

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/Nagoya#17]
Creating an initial Figma draft design of the website. 

Key things to lock are:
- Basic navigation process
- Color scheme
- Typography
- V1 Features
- General organization of content

**Comment by GeoffreyXue** [comment]
@cmg777 Hi, sorry for the delayed update - I've been working the Figma design for a bit and diving into the learning process. Here's an invite to the Figma:

[https://www.figma.com/team_invite/redeem/gDRePe4MxIKmfE7JIpDier](https://www.figma.com/team_invite/redeem/gDRePe4MxIKmfE7JIpDier)

To give a brief overview of the project:
- On each Figma diagram, there exists pages which display frames. You can see your pages on the top left - Currently there exists a "Main", "Components", and "Design Style" page
    - The Main page is where the actual website design is
    - The Components page has Figma components, which resuable modules that can be inserted in the project (see button for example)
    - The Design Style page overviews the color and typography standard for the project

Currently we have some unfinalized templates for each of the pages. If there's any features forgotten (outside of those mentioned TODO in the comments), please let us know!

Unfortunately next week is exam week, so this project will probably be put on hold for a bit. We'll be picking this back up after exam season for more work and any refactors necessary.

**Comment by cmg777** [comment]
Thank you very much @GeoffreyXue.  I like the design. If some additional features are needed, I will let you know.
All the best with the exam season.
